### ISSUE TITLE
CuppaCMS has SQL injection vulnerability

### ISSUE THREAD

**Issue by anquanfuwu** [CuppaCMS/CuppaCMS#5]
Affected software: CuppaCMS

Type of vulnerability: SQL injection

Discovered by: darkrerror

SQL Injection in administrator/classes/ajax/functions.php with parameter reference_id

function updateUserTableLog(){
                if(!@$_POST["reference_id"]) echo "1";
                $cuppa = Cuppa::getInstance();
                $data = new stdClass();
                $data->user_id_updating = "'".$cuppa->user->getVar("id")."'";
                $data->date_updating = "'".date('Y-m-d H:i:s')."'";
                $data->table_name = "'".$_POST["table_name"]."'";
                $data->reference_id = "'".$_POST["reference_id"]."'";
                $result = $cuppa->dataBase->add($cuppa->configuration->table_prefix."tables_log", $data);
                echo $result;

POST request screenshot:
![image](https://user-images.githubusercontent.com/25028673/48188775-819e8e00-e379-11e8-9de7-8911919b5007.png)

sqlmap tool screenshot
![image](https://user-images.githubusercontent.com/25028673/48188870-b6aae080-e379-11e8-9cd8-6313ba8b5720.png)

**Comment by tufik2** [comment]
This issue was fixed in the last release...

**Comment by tufik2** [comment]
This issue was fixed in the last commit...

**Comment by anquanfuwu** [comment]
> This issue was fixed in the last commit...

thanks
